### ISSUE TITLE
Triple Store implementation design

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/oteapi-services#103]
@Treesarj @quaat @jesper-friis I am unsure about the current triple store implementation.

It is implemented as a Data Cache-like Python class in `oteapi-core`, but also with a separate endpoint in #97 to fetch data from it.
Unlike the redis service in this repository and the data cache in `oteapi-core`, this makes the triple store span over both repositories, which I don't think is desireable.

While it might not be desireable, it may also be unavoidable.

Hence, I'd like to go over the design of how the triple store should be implemented again, and possibly update it - hopefully keeping it only in one of the repositories or as an alternative have a clear separation of what is the backend implementation and what is the general CRUD interface to do triple store transactions.

**Comment by Treesarj** [comment]
closing this issue because : https://github.com/EMMC-ASBL/oteapi-services/issues/397
