### ISSUE TITLE
Issue with TripleStoreConfig on latest oteapi image 

### ISSUE THREAD

**Issue by daniel-sintef** [EMMC-ASBL/oteapi-services#112]
There seems to be something wrong with the latest oteapi image on ghcr.io/emmc-asbl/oteapi. When I try to run the services with this image I get an ImportError for the TripleStoreConfig:
`
ImportError: cannot import name 'TripleStoreConfig' from 'oteapi.models' (/oteapi-core/oteapi/models/__init__.py).`

Changing the image in docker-compose_dev from ghcr.io/emmc-asbl/oteapi:${DOCKER_OTEAPI_VERSION:-latest} to ghcr.io/emmc-asbl/oteapi:0.1.5 solves the problem 

(Thanks @kriwiik for writing the first part up) 

To reproduce the issue checkout the following git repos with the following branches:
 oteapi-core: 22a17388d085dd5c4ac25597e5378b03b4da0fbf
 oteapi-dlite: f802bceada74369e6cd5dc4f2c26f4daba820c36
 oteapi-pgbs: 5ecd0616922b3ed6083622ec84acaee1ff068776

And export the paths so that they can be found by docker-compose
`$export PATH_TO_OTEAPI_DLITE=<path-to-your>/oteapi-dlite`
`$export PATH_TO_OTEAPI_CORE=<path-to-your>/oteapi-core`

Then cd into the oteapi-pgbs branch and pull the latest docker image

`$docker-compose -f docker-compose_dev.yml pull`

And run try to start up docker-compose, you will get the error above

`$docker-compose -f docker-compose_dev.yml up`

Note that switching to the 0.1.5 release, either by changing docker-compose_dev.yml, or, by checking out 
oteapi-pgbs 3abb09fedc38aa052e924c1dd3c62a24a17401b1
fixes the issue. To our knowledge, 0.1.5, was the last functioning version

**Comment by CasperWA** [comment]
You're using a too old version of `oteapi-core`. Use the latest one.
The commit you're referencing has 1851cb1 as parent commit, which is prior to the PR that implements the triple store. See the commit history [here](https://github.com/EMMC-ASBL/oteapi-core/commits/master).
