### ISSUE TITLE
Pylint fails with useless-option-value / R0022

### ISSUE THREAD

**Issue by quaat** [EMMC-ASBL/oteapi-services#182]
Building the services docker container fails at pre-commit pylint-check with:

pylint - tests...........................................................Failed
- hook id: pylint-tests
- exit code: 8

************* Module filter
tests/static/test_strategies/filter.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
************* Module mapping
tests/static/test_strategies/mapping.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
************* Module resource
tests/static/test_strategies/resource.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
************* Module parse
tests/static/test_strategies/parse.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
************* Module transformation
tests/static/test_strategies/transformation.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
************* Module download
tests/static/test_strategies/download.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
************* Module function
tests/static/test_strategies/function.py:2:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)

**Comment by CasperWA** [comment]
Exciting - they've removed this option now as well. Great.
These should be removed then.

**Comment by CasperWA** [comment]
Please put me as reviewer on your upcoming PR.
