### ISSUE TITLE
Versioning suggestion

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/oteapi-services#71]
Since this package will not be published on PyPI or a similar Python package index, but rather the focus is on the generated container/Docker image, I have a suggestion concerning how we could do it here, mainly evolving around `oteapi-core`.

Whenever pushing to `master` we publish two different tag-versions of the `ghcr.io/emmc-asbl/oteapi` container image:
- `latest` (this is the only one in existence now and this is what is also happening now from the CD workflows.
- `vMAJOR.MINOR.PATCH`, where this version matches the current requirement version of `oteapi-core` (as of now it would then be `v0.1.2`).

In this way, when the `oteapi-core` requirement changes, the version tag will also change, and then the latest version of `oteapi-services` (and thereby the FastAPI application) that supported a given `oteapi-core` version will match the equivalent container image tag.

The version provided in [`app/__init__.py`](https://github.com/EMMC-ASBL/oteapi-services/blob/master/app/__init__.py) will not really change then, and will have no real value - it can essentially even be removed as it's not referenced anywhere.

**Comment by CasperWA** [comment]
As a note, it seems the general "standard" for version tags is to exclude the `v` prefix, so the version tag would be `MAJOR.MINOR.PATCH`.

**Comment by CasperWA** [comment]
After discussing this with @quaat we have come up with the following (sort of) [semantic versioning](https://semver.org) scheme:

`<API version>.<CalVer>.<Build #>`

Container images will only be released for the major version, i.e., the API version - and `latest`.

- The `latest` image will be built from the latest commit on `master` (as is the case now).
- The API version image will be built from the latest commit on `master` as well, but a new image version will come to exist when the API version is bumped from `1` to `2` (and so on).

As an example with different versions, see the table below.

| Full version | Container image |
|---|---|
| 1.20220407.248 | |
| 1.20220407.249 | |
| 1.20220408.250 | |
| 1.20220408.251 | X (tag: `1`) |
| 2.20220407.321 | X (tag: `2`, `latest`) |

The table also provides examples of the values for the versioning syntax scheme.

- <API version>: The "major" version.
  The number, which is also reflected in the URL path of the API as a path prefix (current default: `/api/v1`).
- <CalVer>: The "minor" version.
  Based on [calendar versioning](https://calver.org), this will be YYYY0M0D, meaning it will always be 8 characters long, no matter if the day or month are single digit days or months.
- <Build #>: The "patch" version.
  This is the commit number in the `master` branch. At the time of writing, there are 250 commits in `master`, meaning `250` is the current build #.
  The build number can be retrieved by writing the following command in a terminal (on a unix-based system):
  Build #: `git log master --pretty=oneline | wc -l`

The full container image name with tags will be:
- `ghcr.io/emmc-asbl/oteapi:latest`
- `ghcr.io/emmc-asbl/oteapi:<API version>` (e.g., `ghcr.io/emmc-asbl/oteapi:1`)

Finally, it's important to note that the `__version__` variable in `app/__init__.py` will always be updated with the full version - this is the only place it will be documented.

**Comment by daniel-sintef** [comment]
This seems well-thought out and I'm happy with it. Thanks for showing the digest sha link https://github.com/EMMC-ASBL/oteapi-services/pkgs/container/oteapi/versions?filters%5Bversion_type%5D=untagged which will be useful if I need it for debugging later.
