### ISSUE TITLE
Development image does not start correctly

### ISSUE THREAD

**Issue by xAlessandroC** [EMMC-ASBL/oteapi-services#89]
# Steps to reproduce the error
1. Clone the #87 version of oteapi-services repo
2. Build a development local image
```
docker build --rm -f Dockerfile --label "ontotrans.oteapi=development" --target development -t "ontotrans/oteapi-development:latest" .
```
3. change the oteapi image in the **docker-compose.yml** file
 **Remove**: image: ghcr.io/emmc-asbl/oteapi:${DOCKER_OTEAPI_VERSION:-latest}
**Add**: image: ontotrans/oteapi-development:latest
4. start the containers
```
docker-compose up -d
```
# Error
The **oteapi-services-oteapi-1 container** does not start and in the log I get the following error
```
/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by CasperWA** [comment]
This shouldn't be an issue any longer. Please always clone the `master` version of this repository unless you are testing a PR :)

**Comment by CasperWA** [comment]
Also - this is not how a docker-compose file works.
The `image` key points to online container repositories. In this case the oteapi container image is hosted on the GitHub container registry (ghcr.io). By default the Docker Hub container registry (hub.docker.com) will be used.

**Comment by CasperWA** [comment]
To use docker-compose in development mode see the documentation [here](https://github.com/EMMC-ASBL/oteapi-services#run-with-docker-compose-development). You essentially need to use the different docker-compose file (`docker-compose_dev.yml`), which will build the oteapi image from the Dockerfile, using the `development` target (essentially running the first command you're referencing above).

**Comment by xAlessandroC** [comment]
Thank you for your advice Casper, I'll try to build and use the development image as you suggest and let you know!

**Comment by CasperWA** [comment]
@xAlessandroC is still the case or can we close this issue?

**Comment by xAlessandroC** [comment]
Hi Casper, sorry for not letting you know, I have been busy with other projects, and I haven't tried yet. I hope to make it this week

**Comment by xAlessandroC** [comment]
Hi Casper, I tried, as you suggested, to clone the `master` repository and use the `docker-compose_dev`.yml file but I still have the same problem: 
```
/usr/bin/env: ‘bash\r’: No such file or directory
```
The only change I made was to replace the ${PWD} volume variable with the path to my working directory (which is the one of the repo). I also saw that the docker-compose file shown [here](https://github.com/EMMC-ASBL/oteapi-services#oteapi-plugin-repositories) is a bit different. Am I doing something wrong in the deployment? I'm on a windows 10 machine.

**Comment by CasperWA** [comment]
This is a Windows issue. It uses an extra `\r` for line endings (`\r\n` versus just `\n` on Linux and macOS systems).
Try to change line endings (if you can). The specific code that it's executing will be in a Linux environment, hence it needs the appropriate line endings.
You should set up your git to also don't change line endings to Windows line endings. I'd recommend using Linux line endings always, since Windows can handle this fine, but not the other way around.

[Here](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)'s some documentation from GitHub.

**Comment by xAlessandroC** [comment]
I see but another point comes to my mind. Before I just tried to run the repo with no plugins inside, so just oteapi-core. So, if there isn't my code (ontokb-plugin) in the image with the wrong line endings why should the error appear? Maybe when I clone the repo or build the image my PC changes the line endings?

**Comment by xAlessandroC** [comment]
I think I solved the problem, I changed all the line endings of the cloned `oteapi-services` repo and now it seems to work. Now I can return to the original problem :)
I think you can close the issue, thank you very much for your time!

**Comment by CasperWA** [comment]
> (...) Maybe when I clone the repo or build the image my PC changes the line endings?

Exactly this. This is what happens :)

And great to hear it solved it - changing the line endings.
Looking forward to helping with the original problem now 😄
