### ISSUE TITLE
Use pydantic models as Response Model

### ISSUE THREAD

**Issue by CasperWA** [EMMC-ASBL/oteapi-services#9]
Consider creating pydantic models to outline the API responses, query parameters and more.

The benefit of this will be nicer documentation in the `/docs` and `/redoc` endpoints as well as automatic type validation.

**Comment by pscff** [comment]
Good point. At the moment, the responses are plain json. Do we need to declare any additional pydantic models? I guess most return models are already present. Example for the endpoint `GET /api/v1/datasource/{resource_id}/info` I guess would simply be

```
@router.get("/{resource_id}/info", response_model=ResourceConfig)
async def info_dataresource(
    resource_id: str,
    cache: Redis = Depends(depends_redis),
) -> dict:
    """Get data resource info"""
    resource_info_json = json.loads(await cache.get(resource_id))
    resource_info = ResourceConfig(**resource_info_json)

    return resource_info.dict()
```

See: https://fastapi.tiangolo.com/tutorial/response-model/

Since this **is changing the OpenAPI Specs** (and everyone involved in creating client code will be affected), I am adding a new label.

**Comment by CasperWA** [comment]
> Good point. At the moment, the responses are plain json. Do we need to declare any additional pydantic models? I guess most return models are already present. Example for the endpoint `GET /api/v1/datasource/{resource_id}/info` I guess would simply be
> 
> ```python
> @router.get("/{resource_id}/info", response_model=ResourceConfig)
> async def info_dataresource(
>     resource_id: str,
>     cache: Redis = Depends(depends_redis),
> ) -> dict:
>     """Get data resource info"""
>     resource_info_json = json.loads(await cache.get(resource_id))
>     resource_info = ResourceConfig(**resource_info_json)
> 
>     return resource_info.dict()
> ```
> ...

One wouldn't need to convert to `dict()`, but could simply return the model as is, i.e., it would become:


```python
@router.get("/{resource_id}/info", response_model=ResourceConfig)
async def info_dataresource(
    resource_id: str,
    cache: Redis = Depends(depends_redis),
) -> ResourceConfig:
    """Get data resource info"""
    resource_info_json = json.loads(await cache.get(resource_id))
    return ResourceConfig(**resource_info_json)
```

I really like this way of doing it and FastAPI is built with this in mind as well with several parameters in the `@router.get()` decorator function to manipulate and control the transformation from model (`ResourceConfig`) to actual HTTP response.

**Comment by pscff** [comment]
Even better. Also having `ResourceConfig` as return value in the function annotation! Any thoughts regarding additional path operation decorator parameters such as `response_model_exclude_unset=True` which would supress response with unset values?

**Comment by CasperWA** [comment]
> Even better. Also having `ResourceConfig` as return value in the function annotation! Any thoughts regarding additional path operation decorator parameters such as `response_model_exclude_unset=True` which would supress response with unset values?

🥳 

Concerning the additional path operation decorator parameters we can discuss together or try out different setting to settle on what fits best for us.
I would even go as far as explicitly setting the defaults for some of these parameters to be as transparent and explicit as possible.

The more interesting part (for great documentation) is also that any `kwargs` will be added to the generated OpenAPI file. And some parameters have been proxied through explicitly as well. Such as adding response models for error codes (which is nice as this will add what error codes may be returned from an entry point and what the response looks like) and full examples as well. But the examples are easier to add directly to the pydantic models, though, in most cases.

In any case, I implore you to play around - assign yourself to this issue, create a branch and start setting up a response model and test out what is actually returned when changing the path operation decorator parameters :)

**Comment by pscff** [comment]
Agreed, I just created a branch and will start implementing some obvious ResponseModels - similar to the example above - for all of us to look at.

Just one point: This is changing the OpenAPI Specs, and we would need a general agreement on what changes we want. In principle, **OpenAPI Specs for the OTEAPi-services repo should never/rarely change** because anyone involved in client-side code development (a.k.a. *OTE Demonstration*)  - including myself - will see their code break. Same holds for the OTELib repo which is also broken in many places now.

**Comment by pscff** [comment]
**Current state of implemeting pydantic models in this branch - to be discussed**

I take `GET /{resource_id}/info` as an example here to describe the implementation:

```
@router.get(
    "/{resource_id}/info",
    response_model=ResourceConfig,
    responses={
        HTTP_404_NOT_FOUND: {"model": HTTPNotFoundError},
    },
)
async def info_dataresource(
    resource_id: str,
    cache: Redis = Depends(depends_redis),
) -> ResourceConfig:
    """Get data resource info"""

    if not await cache.exists(resource_id):
        raise httpexception_404_item_id_does_not_exist(resource_id, "resource_id")
    resource_info_json = json.loads(await cache.get(resource_id))
    return ResourceConfig(**resource_info_json)

```

The endpoint now has:
* The model for the 200 response: `response_model=ResourceConfig` where `ResourceConfig` is already defined in oteapi-core. So we dont need to define an additional response model for this endpoint. See: https://fastapi.tiangolo.com/tutorial/response-model
* In addition, we need a Response model for a 404 response in this case. The implementation is using this pattern: https://fastapi.tiangolo.com/advanced/additional-responses/

For some of the endpoints, additional models are required for responses and also for parameters. For this, I added a package `app.models` for implementing the respective pydantic models. At the moment, there is a very generic response model `Status` which is simply `Dict[str, Any]`. For this to work, we need to use pydantic's `__root__` model which has numerous issues with fastAPI: https://github.com/tiangolo/fastapi/issues/911.

Plus, we cannot return `Status` but must return `dict` as illustrated for the following endpoint:

```
@router.post(
    "/",
    response_model=Status,
    response_model_exclude_unset=True,
    responses={
        HTTP_404_NOT_FOUND: {"model": HTTPNotFoundError},
    },
)
async def create_dataresource(
    config: ResourceConfig,
    session_id: Optional[str] = None,
    cache: Redis = Depends(depends_redis),
) -> Dict[str, Any]:

    resource_id = IDPREDIX + str(uuid4())

    await cache.set(resource_id, config.json())
    if session_id:
        if not await cache.exists(session_id):
            raise httpexception_404_item_id_does_not_exist(session_id, "session_id")
        await _update_session_list_item(
            session_id, "resource_info", [resource_id], cache
        )
    return dict(resource_id=resource_id)
```

It would be better to have a less generic `Status` response, or a different response model for different endpoints. That would then use the respective pydantic model for validation etc. For the generic `Status` response above, we wouldnt want to use a pydantic model in the first case. So, once we decide on what to "respond", we could build on the curent `Status` implemention.

**Additional thoughts**:
* It would be good to decide on the response model for the endpoints and have a less generic `Status` response.
* For some endpoints, the actual response depends on the strategy beeing used (See following example)

```
@router.get("/{resource_id}",...)
async def read_dataresource(
    resource_id: str, ...
...) -> Dict[str, Any]:
    ...
    parse_strategy = create_parse_strategy(resource_config)
    output = parse_strategy.parse(session_data)
    ...
    return output
```

What `output` is depends on what `parse_strategs.parse` from oteapi-core (or a plugin) would return. Looking at some of the strategies, these are dicts with varying contents as of now. Would be good to use pydantic models for `output` in the first place. Then it becomes cristal-clear what a - say parse - strategy is supposed to return. Would greatly help people developing plugins.

**Comment by CasperWA** [comment]
This is great work - and indeed what I had in mind for where this should go.
You're completely right about the `Status` model. We should instead create a model specific for each endpoint, where relevant, and use them as responses (in my opinion).

Another note: It would be great if we can follow the progress of your work - either through a draft PR or simply by working on a branch in the current repository? The branch naming convention we're currently using is the following: `<initials>/<close|fix>-<issue #>-<descriptive name>`, e.g., `ps/close-9-use_pydantic_models_as_responses`.

Could we also perhaps have a meeting to discuss the work here? I think it might be easier/faster to discuss it in that way concerning where we're at now.

**Comment by CasperWA** [comment]
> Another note: It would be great if we can follow the progress of your work - either through a draft PR or simply by working on a branch in the current repository? The branch naming convention we're currently using is the following: `<initials>/<close|fix>-<issue #>-<descriptive name>`, e.g., `ps/close-9-use_pydantic_models_as_responses`.

Never mind - I just saw you have the branch [fix_issue06_pydantic_response_models](https://github.com/EMMC-ASBL/oteapi-services/tree/fix_issue06_pydantic_response_models) 😄
